### ISSUE TITLE
Add SSL support

### ISSUE THREAD

**Issue by aclark4life** [dcpython/dcpython-django-1#97]
Due to #95 we'll need to re-add SSL support without relying on platform credits from Heroku

**Comment by aclark4life** [comment]
Possibly helpful: https://letsencrypt.org/

**Comment by Deesus** [comment]
Why don't you just setup a PayPal (or another 3rd party payment processor) donation button for the site? Because PayPal redirects the user, and all the sensitive information the user enters is done on _their_ domain, you don't need SSL. See [this FAQ](https://www.sslshopper.com/article-do-i-need-an-ssl-certificate-for-my-website.html) and [this SO post](http://stackoverflow.com/questions/16987296/does-my-website-require-https-ssl-for-paypal-express-checkout-for-recurring-paym).

PayPal has [step-by-step instructions](https://www.paypal.com/webapps/mpp/get-started/donate-button) on setting up a donations button/form selection. You would then just copy the generated code onto your template/page.

You can still keep the Heroku workflow, and you can implement your own SSL certificates later down the line if you decide to do so.

**Comment by arusahni** [comment]
Good news - LetsEncrypt enters open beta on 12/3: https://letsencrypt.org/2015/11/12/public-beta-timing.html
